arch: "poundnet"
resume: null
name: "poundnet_ViTL_Progan"

logger:
  use_wandb: false
  offline: true
  project: "PoundNet"

train:
  pipeline: engine.poundnet_trainer
  accelerator: "gpu"
  gpu_ids: 1
  seed: 38534
  train_epochs: 1
  gradient_accumulation_steps: 1
  check_val_every_n_epoch: 1
  precision: "16"

  a: 1
  b: 1
  c: 1

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1e-4
    weight_decay: 1e-3
    betas: [0.9, 0.999]

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: ${train.train_epochs}

model:
  NAME: "ViT-L/14"
  N_CTX_VISION: 16
  N_CTX_TEXT: 16
  CTX_INIT: false
  PROMPT_DEPTH_VISION: 8
  PROMPT_DEPTH_TEXT: 8
  PROMPT_NUM_TEXT: 1

datasets:
  base_path: "/path/to/DF-arrow"

  train:
    source:
      - target: data.ArrowDatasets
        data_root: ${datasets.base_path}/ForenSynths
        sub_sets:
          - "airplane"
          - "bird"
          - "bottle"
          - "car"
          - "chair"
          - "diningtable"
          - "horse"
          - "person"
          - "sheep"
          - "train"
          - "bicycle"
          - "boat"
          - "bus"
          - "cat"
          - "cow"
          - "dog"
          - "motorbike"
          - "pottedplant"
          - "sofa"
          - "tvmonitor"
        split: "train_binary"

    multicalss_names:
      - "airplane"
      - "bird"
      - "bottle"
      - "car"
      - "chair"
      - "diningtable"
      - "horse"
      - "person"
      - "sheep"
      - "train"
      - "bicycle"
      - "boat"
      - "bus"
      - "cat"
      - "cow"
      - "dog"
      - "motorbike"
      - "pottedplant"
      - "sofa"
      - "tvmonitor"

    batch_size: 128
    loader_workers: 8
    trsf:
      - _target_: torchvision.transforms.Resize
        size: 256
      - _target_: torchvision.transforms.RandomResizedCrop
        size: 224
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: data.DataAugment
        blur_prob: 0.1
        blur_sig: [0.0, 3.0]
        jpg_prob: 0.1
        jpg_method: ["cv2", "pil"]
        jpg_qual: [60, 100]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]

  val:
    source:
      - target: data.ArrowDatasets
        data_root: ${datasets.base_path}/DIF
        sub_sets: ["dalle_2", "dalle_mini", "glide", "mj", "sd14", "sd21"]
        split: "test"
        benchmark_name: "DIF"

    batch_size: 128
    loader_workers: 8
    trsf:
      - _target_: data.RandomCompress
        method: "JPEG"
        qf: [70, 100]
      - _target_: torchvision.transforms.Resize
        size: 256
      - _target_: torchvision.transforms.CenterCrop
        size: 224
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]
